apiVersion: v1
kind: service
metadata:
   name: nginx
   labels:
      purpose: service-demo
spec:
  selector:
    purpose: service-demo
    project: roboshop
    environment: dev


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    environment: dev
spec:
 containers:
 - name: nginx
   image: nginx